### ISSUE TITLE
services.throttled.enable fails to build

### ISSUE THREAD

**Issue by AlexChalk** [NixOS/nixos-hardware#937]
System info:

- OS: NixOS 24.05pre622847.b211b392b848 (Uakari) x86_64
- Host: LENOVO 20L6SJDU00 (t480)
- Kernel: 6.6.30

I recently tried to `nixos-rebuild` my system and got the following error: 
```
× throttled.service - Stop Intel throttling
     Loaded: loaded (/etc/systemd/system/throttled.service; enabled; preset: enabled)
    Drop-In: /nix/store/8zm6yajvjc9ys9awm4fg6nlcmzpvdj8h-system-units/throttled.service.d
             └─overrides.conf
     Active: failed (Result: exit-code) since Thu 2024-05-09 22:29:53 EDT; 107ms ago
   Duration: 75ms
    Process: 3894 ExecStart=/nix/store/cvsy0h3s7s14s42n83gw9wi1q55jqwfb-throttled-0.10.0/bin/throttled.py (code=exited, status=1/FAILURE)
   Main PID: 3894 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 74ms

May 09 22:29:53 nixos systemd[1]: Started Stop Intel throttling.
May 09 22:29:53 nixos throttled.py[3894]: Traceback (most recent call last):
May 09 22:29:53 nixos throttled.py[3894]:   File "/nix/store/cvsy0h3s7s14s42n83gw9wi1q55jqwfb-throttled-0.10.0/bin/.throttled.py-wrapped", line 25, in <module>
May 09 22:29:53 nixos throttled.py[3894]:     from gi.repository import GLib
May 09 22:29:53 nixos throttled.py[3894]:   File "/nix/store/40cddha2iiqzbqd6dpal3rlrgvb4p0yc-python3.11-pygobject-3.48.2/lib/python3.11/site-packages/gi/importer.py", line 133, in create_module
May 09 22:29:53 nixos throttled.py[3894]:     raise ImportError('cannot import name %s, '
May 09 22:29:53 nixos throttled.py[3894]: ImportError: cannot import name GLib, introspection typelib not found
May 09 22:29:53 nixos systemd[1]: throttled.service: Main process exited, code=exited, status=1/FAILURE
May 09 22:29:53 nixos systemd[1]: throttled.service: Failed with result 'exit-code'.
warning: error(s) occurred while switching to the new configuration
```

I'm happy to help debug, but I'd appreciate advice on where to start. I assume this error is due to https://github.com/NixOS/nixos-hardware/blob/a4e2b7909fc1bdf30c30ef21d388fde0b5cdde4a/lenovo/thinkpad/t480/default.nix#L11 Thanks!

**Comment by tomodachi94** [comment]
https://github.com/NixOS/nixpkgs/pull/309377 was just merged and appears to fix the error. Can you update your Nixpkgs instance?

**Comment by AlexChalk** [comment]
Amazing, thanks @tomodachi94.
